version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ⬆
  # Python uv
  - package-ecosystem: uv
    directory: /server
    schedule:
      interval: daily
    commit-message:
      prefix: ⬆
  # npm
  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: daily
    commit-message:
      prefix: ⬆
